version: "3"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./FrontEnd/html:/var/www/html/
        links:
            - db
        networks:
            app_subnet:
                ipv4_address: 172.16.1.3    
    db2:
        image: mysql:5.7
        ports:
            - "3307:3306"
        restart: always
        environment:
            - MYSQL_USER=dbuser
            - MYSQL_PASSWORD=dbpassword
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=gamemaster_db
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - ./BackEnd/GameMasterService/db2:/docker-entrypoint-initdb.d
            - persistent2:/var/lib/mysql 
        networks:
            app_subnet:   
                ipv4_address: 172.16.1.8             
    db:
        image: mysql:5.7
        expose:
            - "3306" 
        ports:
            - "3306:3306"
        restart: always
        environment:
            - MYSQL_USER=dbuser
            - MYSQL_PASSWORD=dbpassword
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=mydatabase
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - ./BackEnd/authentication_service/db:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql 
        networks:
            app_subnet:
                ipv4_address: 172.16.1.7   
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db
            - db2 
        ports:
            - 8000:80
        restart: always 
        environment:
            PMA_ARBITRARY: 1 
    playmaster:
        build: ./BackEnd/PlayMasterService
        depends_on:
            - db
        ports:
            - 5001:5001
        links: 
            - db
        networks:
            app_subnet:
                ipv4_address: 172.16.1.2   
    authentication: 
        build: ./BackEnd/authentication_service 
        depends_on:
            - db
        ports: 
            - 5000:5000
        links:
            - db 
        networks: 
            app_subnet:
                ipv4_address: 172.16.1.4 
    gamemaster: 
        build: ./BackEnd/GameMasterService 
        restart: always 
        depends_on:
            - db2
        ports: 
            - 5002:5000
        links:
            - db2 
        networks: 
            app_subnet:
                ipv4_address: 172.16.1.6 
networks:
    app_subnet: 
        ipam:
            config: 
                - subnet: 172.16.1.0/24   
volumes: 
    persistent:
    persistent2: 



        
            
        
        
