version : '2'

services:
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: mydatabase 
    ports: 
    - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    environment:
        MYSQL_USER: test
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
    volumes:
    - ./db:/docker-entrypoint-initdb.d

volumes:
    persistent: 